name: 'Auto Merge on Label'

on:
  pull_request_target:
    types: [labeled]

jobs:
  merge-on-auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto-merge labeled PRs when checks pass
        uses: pascalgn/automerge-action@v0.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          label: auto-merge
          # Require status checks to pass before merging
          required_checks: 'true'
